alesantoscoz/DEV003-social-network

package.json
-Se agrego opción de argumento de VITE para correr la app en mobile/tablet.
=> feat: see web in other devices

src/index.html, src/main.css, src/public/login.css, src/view/login.js
-Optimización de estilos CSS en la vista Login
=> feature: styles Login

src/index.html, src/public/cakebook.css, src/public/register.css, src/view/cakebook.js, src/view/login.js, src/view/register.js
=> feature: view register

src/view/login.js, src/view/register.js
-form.reset();
-modificación del placeholder en el input user en el login
=> feat: detalles en JS form register

src/view/login.js, src/view/register.js
Se implementó signInWithEmailAndPassword para entrar a la red social
Se implementó sistema de alertas de acuerdo a los errores firebase
=> Autenticación logueo y sistema de alertas

src/controllers/authController.js, src/main.js, src/view/cakebook.js, src/view/login.js
=> feat: cierre de sesión con firebase.

src/view/cakebook.js, src/view/login.js, src/view/register.js
-Login con google con Firebase Auth.
-Función de observador de estado de autenticación de usuarios.
=> feat: login con google

src/view/register.js
=> redireccion despues de registro

src/lib/google-auth.js, src/view/login.js, src/view/register.js
-Google signup en la vista de register
-Refactor de código en el login y register.
=> feat: google signup and refactor login and register

src/index.html, src/public/cakebook.css, src/view/cakebook.js
=> feat: optimización cakebook

src/index.html, src/public/cakebook.css, src/view/cakebook.js, src/view/register.js
implementar footer en index.html
display none
querySelector en view cakebook
display flex
=> arreglo footer

src/public/cakebook.css, src/view/cakebook.js
-Agregar estilos box- createPost
=> feat: css- post view-cakebook

src/lib/firebase-app.js, src/view/cakebook.js
-Mostrar los post, obteniendo la data de firebase.
=> feat: get data firebase-firestore de la coleccion posts

src/view/cakebook.js
-Al crear un post sobreescribía el post existente.
-Listado no se actualizaba al crear un post.
=> bugfix: load posts realtime

src/view/cakebook.js
- Mostrar nombre de usuario logueado con google y fecha de creación de post.
=> cambios userName

src/view/cakebook.js
=> feat: focus Input

src/controllers/authController.js, src/index.html, src/public/profile.css, src/routes/route.js, src/view/profile.js
=> vista profile

src/lib/firebase-app.js, src/public/cakebook.css, src/view/cakebook.js
=> feat: delete post

src/view/cakebook.js
- Solución bug de los likes en cakebook
=> bugfix: errores en likes cakebook

src/view/cakebook.js
- Cambiar '??' por un OR || para que evalúe el tamaño del array y este sea agregado en el texto del <span> cuando sea > 0.
=> bugfix: condición para que no aparezca el 0 likes

src/index.html, src/lib/firebase-app.js, src/lib/google-auth.js, src/main.js, src/view/cakebook.js, src/view/login.js, src/view/profile.js, src/view/register.js, test/index.spec.js
implementación auth en firebase app
funcionalidad botones home y profile en main.js
redirección a home y profile
cargar nombre de usuario en profile.js con displayName
crear post desde /profile (se almacenan en firebase y se imprimen en cakebook, aún no se imprimen en profile)
adicional: cambios en index.spec de OH
=> implementando profile

src/view/profile.js
Solución de errores para la siguiente funcionalidad:
- Proteger vista Profile, solo para usuarios logueados.
- Ocultar footer en la redirección a la vista login.
- Verificar el usuario logueado y cargar vista con su nombre en el perfil.
=> bugfix: Solución de errores en la vista Profile
